COLUMNS_DESC = {
    "products": {
        "product_id": "Unique product identifier (PK). Format: PROD000001",
        "product_name": "Full product name including brand, adjective, and subcategory",
        "brand": "Manufacturer or brand name e.g. Samsung, Amul, Prestige, Boat",
        "category": "Top-level product category (10 categories total)",
        "subcategory": "Specific product type within a category e.g. Mobiles, Cookware",
        "mrp": "Maximum Retail Price (Indian rupees) — original listed price",
        "selling_price": "Actual price customer pays after discount (INR)",
        "discount_percent": "Percentage discount off MRP e.g. 20 means 20% off",
        "rating": "Average customer rating from 1.0 to 5.0",
        "num_ratings": "Total number of rating submissions for this product",
        "num_reviews": "Total number of written text reviews (subset of num_ratings)",
        "is_active": "Whether product is currently listed and visible to buyers",
        "created_at": "Timestamp when product was first added to the catalogue",
    },
    "sellers": {
        "seller_id": "Unique seller identifier (PK). Format: SELL00001",
        "seller_name": "Business name of the seller / merchant",
        "seller_type": "Classification of the seller business type",
        "city": "City where the seller is registered / operates from",
        "state": "Indian state where seller is registered",
        "pincode": "6-digit Indian postal code of seller's address",
        "gstin": "GST Identification Number — 15-char alphanumeric Indian tax ID",
        "rating": "Platform rating for seller from 3.0 to 5.0 based on performance",
        "total_products": "Number of product listings this seller has on the platform",
        "is_verified": "Whether seller has been verified/approved by the platform",
        "joined_at": "Date the seller registered on the platform",
        "bank_account": "Seller's bank account number for payment settlements",
        "ifsc_code": "Bank IFSC code for identifying the seller's bank branch",
    },
    "customers": {
        "customer_id": "Unique customer identifier (PK). Format: CUST000001",
        "first_name": "Customer's first name",
        "last_name": "Customer's last name / surname",
        "email": "Unique email address — used for login and communication",
        "phone": "10-digit Indian mobile number (unique per customer)",
        "date_of_birth": "Customer's date of birth — use for age-based segmentation",
        "gender": "Self-reported gender of the customer",
        "city": "City of the customer's registered delivery address",
        "state": "Indian state of the customer's registered address",
        "pincode": "6-digit postal code of the customer's address",
        "address_line1": "Street-level address (house number, road, area)",
        "is_premium": "Premium membership flag — premium customers get priority & offers",
        "registered_at": "Timestamp when the customer created their account",
    },
    "inventory": {
        "inventory_id": "Unique inventory record identifier (PK)",
        "product_id": "FK → products.product_id — which product this stock belongs to",
        "seller_id": "FK → sellers.seller_id — which seller holds this stock",
        "warehouse": "City name of the fulfillment warehouse holding this stock",
        "quantity_in_stock": "Current number of units available for sale",
        "reorder_level": "Stock threshold below which a reorder should be triggered",
        "reorder_quantity": "Number of units to order when restocking",
        "last_restocked_at": "Date when stock was last replenished",
        "next_restock_at": "Planned date for the next stock replenishment (may be null)",
        "is_in_stock": "Boolean shortcut — true if quantity_in_stock > 0",
        "updated_at": "Timestamp of the last update to this inventory record",
    },
    "orders": {
        "order_id": "Unique order identifier (PK). Format: ORD00000001",
        "customer_id": "FK → customers.customer_id — who placed this order",
        "order_status": "Current status of the order in the fulfillment pipeline",
        "order_date": "Timestamp when the order was placed by the customer",
        "shipped_at": "Timestamp when the order left the warehouse (null if not shipped)",
        "delivered_at": "Timestamp when the order was delivered (null if not delivered)",
        "shipping_type": "Speed tier chosen for delivery",
        "shipping_charge": "Delivery fee charged to the customer in INR (0 = free shipping)",
        "delivery_partner": "Logistics company handling this shipment",
        "tracking_number": "Shipment tracking reference provided by delivery partner",
        "shipping_city": "City to which the order was shipped",
        "shipping_state": "Indian state to which the order was shipped",
        "shipping_pincode": "Delivery pincode",
        "is_gift": "Whether the order was marked as a gift by the customer",
        "coupon_code": "Discount coupon code applied (empty string = no coupon)",
        "coupon_discount": "INR amount discounted due to coupon (0 if no coupon)",
    },
    "order_items": {
        "order_item_id": "Unique line item identifier (PK). Format: OI000000001",
        "order_id": "FK → orders.order_id — which order this item belongs to",
        "product_id": "FK → products.product_id — which product was purchased",
        "seller_id": "FK → sellers.seller_id — which seller fulfilled this item",
        "quantity": "Number of units of this product in the order",
        "unit_price": "Price per unit at time of purchase (selling_price snapshot)",
        "mrp": "MRP at time of purchase (for discount calculation)",
        "discount_percent": "Discount percentage applied to this item at purchase",
        "subtotal": "unit_price × quantity — total for this line item before GST",
        "gst_rate": "GST slab % applied to this product (5, 12, 18, or 28)",
        "gst_amount": "INR GST charged on this item = subtotal × gst_rate / 100",
        "is_returned": "Whether this specific item was returned by the customer",
    },
    "order_payments": {
        "payment_id": "Unique payment record identifier (PK). Format: PAY000000001",
        "order_id": "FK → orders.order_id — which order this payment is for",
        "payment_method": "Method used to pay — UPI, COD, Credit Card, Debit Card, Net Banking, EMI, Wallet",
        "payment_status": "Outcome of the payment attempt",
        "amount": "INR amount paid in this transaction (may be partial for split payments)",
        "transaction_id": "Reference ID from payment gateway e.g. UPI ref, card last 4 digits",
        "payment_at": "Timestamp when payment was made (COD = on delivery date)",
        "emi_months": "EMI tenure in months — null unless payment_method = EMI",
        "wallet_name": "Which wallet app was used — null unless payment_method = Wallet",
        "coupon_discount": "Coupon discount amount applied at payment time (INR)",
        "grand_total": "Full order total including shipping minus coupon discount (INR)",
    },
}
